import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/main/nav";
import Footer from "@/components/ui/main/footer";

const plusJakarta = Plus_Jakarta_Sans({ subsets: ["latin", "latin-ext"] });

export const metadata: Metadata = {
  title: "Next Blog App",
  description: "Generated by dezmymachine",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakarta.className}>
        <Nav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
